name: devblog

services:
  postgresql:
    image: postgres:latest
    env_file:
      - ./postgresql/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql/setup:/docker-entrypoint-initdb.d
    ports:
      - 5435:5432

  blog-backend:
    image: blog-backend
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - .backend.env
    depends_on:
      - postgresql
    ports:
      - 3000:3000
      
  blog-frontend:
    image: blog-frontend
    build:
      context: ./frontend
    restart: unless-stopped
    env_file:
      - .frontend.env
    ports:
      - 80:3000

volumes:
  db_data: